openapi: 3.0.0
info:
  title: API Tic-Tac
  version: 0.1.0
servers:
  - url: http://127.0.0.1:5000/
    description: Dev server
paths:
  /new-game:
    get:
      summary: Метод создания новой игры
      responses:
        '200':
          description: Условный ответ
          content:
            application/json:
              schema:
                $ref:
